## Bài 1. Tạo Tensor cơ bản

In [1]:
import torch
import numpy as np
import random

In [2]:
a = torch.tensor(
    [[1, 2, 3],
    [4, 5, 6]],
    dtype=torch.int32
)

print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


Tensor a có:
+ kích thước: [2,3]

+ số chiều: 2

+ kiểu dữ liệu: torch.int32

## Bài 2. Tạo các Tensor thường dùng

In [3]:
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.6412, 0.4595, 0.8933, 0.0786],
        [0.5022, 0.9341, 0.1133, 0.3139],
        [0.2712, 0.9999, 0.8134, 0.7536]])
tensor([[ 0.6604,  0.1278, -1.0746,  1.8054],
        [ 0.8960,  0.5613,  0.4545, -0.0566],
        [ 1.1857,  0.2119, -2.1914, -0.5010]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [4]:
f = torch.ones(5,5) * 10
print(f)

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])


Khác nhau của torch.rand() và torch.randn():
+ torch.rand() có phân phối đều và nằm trong đoạn từ 0 đến 1 với xác suất xuất hiện của mọi số trong khoảng [0, 1) là như nhau

+ torch.randn() có phân phối chuẩn và là bất kỳ số thực nào (cả số âm và số dương) với giá trị sinh ra tập trung nhiều nhất xung quanh số 0

## Bài 3. Kiểm tra thông tin Tensor

In [5]:
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


Ý nghĩa của torch.Size([2, 3, 4]):
+ Có 2 khối, mỗi khối 3 chiều, mỗi chiều 4 cột

+ Tổng số phần tử của Tensor là 2 x 3 x 4 = 24

## Bài 4. Slicing và Indexing

In [6]:
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-3.2663e-01, -8.9487e-02, -8.3553e-01,  8.4445e-02,  1.6253e+00],
         [ 7.9329e-01, -6.1135e-01, -2.2642e-01, -1.7089e+00, -5.9251e-03],
         [ 2.8800e+00,  4.5061e-01, -5.5341e-01, -1.5082e+00, -2.3556e+00],
         [-3.1255e-01,  1.0298e+00,  2.7802e-02,  1.1276e+00,  1.1541e+00]],

        [[-1.0165e+00, -3.7293e-01, -3.7037e-01, -1.2610e+00, -6.0604e-01],
         [-3.8370e-01, -2.7908e+00,  6.4309e-02, -2.0311e-01,  2.6132e-03],
         [-2.3473e+00, -4.2786e-01, -6.1179e-01,  3.2563e-01,  9.3111e-01],
         [ 2.9142e-01,  5.2861e-01, -2.2238e-01, -8.3995e-01, -1.2338e+00]],

        [[ 8.8294e-01,  7.2024e-02,  1.4689e+00, -2.2425e-01, -1.0957e+00],
         [-1.3671e-01,  3.3684e-01,  7.5920e-01,  1.9739e+00,  1.2522e+00],
         [-1.7636e+00,  1.1686e+00, -4.3299e-01,  4.4015e-01, -1.1931e+00],
         [ 3.8497e-01, -1.8968e+00,  3.0625e-01,  3.3816e-01, -8.3655e-01]]])

Tensor a[1]:
tensor([[-1.0165e+00, -3.7293e-01, -3.7037e-01, -1.

+ Shape của a[1] là torch.Size([4, 5]).

+ Shape của a[1:, 2:4] là torch.Size([2, 2, 5]).

In [7]:
print("hai phần tử cuối cùng trên chiều thứ ba:")
print(a[:, :, -2:]) 

hai phần tử cuối cùng trên chiều thứ ba:
tensor([[[ 0.0844,  1.6253],
         [-1.7089, -0.0059],
         [-1.5082, -2.3556],
         [ 1.1276,  1.1541]],

        [[-1.2610, -0.6060],
         [-0.2031,  0.0026],
         [ 0.3256,  0.9311],
         [-0.8400, -1.2338]],

        [[-0.2243, -1.0957],
         [ 1.9739,  1.2522],
         [ 0.4401, -1.1931],
         [ 0.3382, -0.8366]]])


## Bài 5. Reshape và Flatten

In [8]:
a = torch.randn(3, 4)

print("Original:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 0.9459, -0.8361,  0.4341,  0.9020],
        [ 0.9467, -0.1845, -0.0931, -0.6341],
        [-0.0308,  0.3182,  2.1529, -0.2729]])

Flatten:
tensor([ 0.9459, -0.8361,  0.4341,  0.9020,  0.9467, -0.1845, -0.0931, -0.6341,
        -0.0308,  0.3182,  2.1529, -0.2729])

Reshape to 3 x 2 x 2:
tensor([[[ 0.9459, -0.8361],
         [ 0.4341,  0.9020]],

        [[ 0.9467, -0.1845],
         [-0.0931, -0.6341]],

        [[-0.0308,  0.3182],
         [ 2.1529, -0.2729]]])


Số phần tử trước và sau khi reshape/flatten luôn không đổi và bằng 3 x 4 =12.

In [9]:
b = a.reshape(2, 6)
print(b)

tensor([[ 0.9459, -0.8361,  0.4341,  0.9020,  0.9467, -0.1845],
        [-0.0931, -0.6341, -0.0308,  0.3182,  2.1529, -0.2729]])


## Bài 6. Phép toán và nhân ma trận

In [10]:
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)

print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-1.0833,  0.8658,  0.6037],
        [-0.0889,  0.4648, -0.0236]])
b:
tensor([[-1.2315,  0.6805,  0.7071],
        [-0.5653, -0.1590,  0.7911]])

a + b:
tensor([[-2.3149,  1.5462,  1.3109],
        [-0.6542,  0.3058,  0.7676]])

a / b:
tensor([[ 0.8797,  1.2723,  0.8537],
        [ 0.1573, -2.9238, -0.0298]])

a^2:
tensor([[1.1736e+00, 7.4955e-01, 3.6446e-01],
        [7.9036e-03, 2.1607e-01, 5.5471e-04]])

Matrix multiplication:
tensor([[ 2.3502,  0.9524],
        [ 0.4091, -0.0423]])


+ a * b là phép nhân từng phần tử tương ứng (element-wise) giữa hai Tensor.  

+ a @ b.T là phép nhân ma trận giữa Tensor a và ma trận chuyển vị của Tensor b.  

+ Khi a có kích thước 2 x 3 và b.T có kích thước 3 x 2, shape của kết quả a @ b.T là torch.Size([2, 2]).  

## Bài 7. Các hàm thống kê trên Tensor

In [11]:
a = torch.randn(3, 4)

print(a)
print("\nMean:")
print(torch.mean(a, dim=1))

print("\nStandard deviation:")
print(torch.std(a, dim=1))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 2.3641,  0.8679,  0.2359,  0.4384],
        [-1.1586,  0.2456, -1.3113, -0.5999],
        [-0.8768, -1.3560, -0.8964,  1.0814]])

Mean:
tensor([ 0.9766, -0.7061, -0.5120])

Standard deviation:
tensor([0.9618, 0.7043, 1.0851])

Cumulative sum:
tensor([[ 2.3641,  3.2320,  3.4680,  3.9064],
        [-1.1586, -0.9130, -2.2243, -2.8242],
        [-0.8768, -2.2328, -3.1292, -2.0478]])


+ Khi đặt dim=0, các hàm toán học sẽ tính toán thu gọn theo chiều dọc.

+ Khi thay bằng dim=1, các phép tính này sẽ được thực hiện theo chiều ngang.

+ Kết quả trả về sẽ có kích thước bằng số hàng của ma trận gốc.

## Bài 8. Autograd cơ bản

In [12]:
x = torch.tensor(
    3.6,
    requires_grad=True
)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [13]:
x = torch.tensor(
    3.6, 
    requires_grad=True
)

y = 3*x**2 + 2*x + 1

y.backward()

print("x.grad =", x.grad) 

x.grad = tensor(23.6000)


## Bài 9. Gradient Descent tìm hệ số đa thức

In [14]:
polynomial = np.poly1d([1, 2, 3])
N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
     X * X,
     X,
     np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 0.2920],
        [-0.5023],
        [ 0.6147]], requires_grad=True)
Learned coefficients:
tensor([[1.0040],
        [1.9956],
        [2.8908]], requires_grad=True)


+ optimizer.zero_grad(): Xóa các giá trị gradient đã tính từ epoch trước để tránh việc cộng dồn gradient. 

+ mse.backward(): Tính toán gradient của hàm mất mát theo các tham số dựa trên đồ thị tính toán.  

+ optimizer.step(): Cập nhật giá trị của các hệ số w dựa trên gradient vừa tính được.  

## Bài 10. Giải hệ phương trình bằng Autograd

In [15]:
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.3705, requires_grad=True)
B = tensor(4.6295, requires_grad=True)
C = tensor(3.6295, requires_grad=True)
D = tensor(2.6295, requires_grad=True)


## Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:
• Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

• Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

• Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

• Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [23]:
X = torch.arange(24) 
print("Original:")
print(X)

print("\nReshape 4x6:")
print(X.reshape(4, 6))

print("\nReshape 2x12:")
print(X.reshape(2, 12))

print("\nReshape 2x3x4:")
print(X.reshape(2, 3, 4))

Original:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

Reshape 4x6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Reshape 2x12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Reshape 2x3x4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [24]:
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A:")
print(A)

print("B:")
print(B)

print("\nA + B:")
print(A + B)
print("\nA * B:")
print(A * B)
print("\nA / B:")
print(A / B)

print("\nMean (dim=0):")
print(torch.mean(A, dim=0))
print("\nStandard deviation (dim=0):")
print(torch.std(A, dim=0))

A:
tensor([[ 2.3986e+00,  1.2299e-03, -5.9240e-01, -3.7703e-01],
        [-8.4428e-01,  1.1051e+00,  1.9689e-01,  1.1641e-01],
        [-4.8818e-03, -5.3501e-01,  8.4327e-01,  8.3100e-01]])
B:
tensor([[ 1.1802,  0.4925, -0.1714,  1.6944],
        [-1.2218,  1.9596,  0.1964, -0.1888],
        [ 1.0333,  1.0762, -0.6606, -0.0248]])

A + B:
tensor([[ 3.5788,  0.4937, -0.7638,  1.3174],
        [-2.0661,  3.0648,  0.3933, -0.0724],
        [ 1.0284,  0.5412,  0.1827,  0.8062]])

A * B:
tensor([[ 2.8308e+00,  6.0568e-04,  1.0154e-01, -6.3885e-01],
        [ 1.0315e+00,  2.1657e+00,  3.8674e-02, -2.1982e-02],
        [-5.0442e-03, -5.7577e-01, -5.5702e-01, -2.0644e-02]])

A / B:
tensor([[ 2.0324e+00,  2.4973e-03,  3.4561e+00, -2.2251e-01],
        [ 6.9102e-01,  5.6396e-01,  1.0024e+00, -6.1641e-01],
        [-4.7246e-03, -4.9713e-01, -1.2766e+00, -3.3450e+01]])

Mean (dim=0):
tensor([0.5165, 0.1905, 0.1493, 0.1901])

Standard deviation (dim=0):
tensor([1.6831, 0.8363, 0.7190, 0.6074])


In [29]:
x = torch.tensor(2.0, requires_grad=True)
y = 2*x**2 + 5*x + 3
y.backward()
print("Đạo hàm bằng Autograd tính dy/dx tại x = 2:")
print("x.grad =", x.grad.item())

print("\nĐạo hàm bằng tính tay: 4*x + 5 =", 4 * 2.0 + 5)

Đạo hàm bằng Autograd tính dy/dx tại x = 2:
x.grad = 13.0

Đạo hàm bằng tính tay: 4*x + 5 = 13.0


In [31]:
print("y = 2x^2 - 3x + 5")

X_np = np.random.randn(20, 1) * 5
Y_np = 2 * (X_np**2) - 3 * X_np + 5
XX = np.hstack([
    X_np**2, 
    X_np, 
    np.ones_like(X_np)
])

w = torch.randn(3, 1, requires_grad=True)
x_tensor = torch.tensor(XX, dtype=torch.float32)
y_tensor = torch.tensor(Y_np, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.1)

print("\nInitial coefficients:")
print(w)

for epoch in range(1500):
    optimizer.zero_grad()
    y_pred = x_tensor @ w
    mse = torch.mean(torch.square(y_tensor - y_pred))
    mse.backward()
    optimizer.step()

print("\nLearned coefficients:")
print(w)

y = 2x^2 - 3x + 5

Initial coefficients:
tensor([[1.6453],
        [0.8030],
        [0.0139]], requires_grad=True)

Learned coefficients:
tensor([[ 1.9964],
        [-3.0025],
        [ 4.9966]], requires_grad=True)
